version: '3'

services:
  db:
    image: postgres:11.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=idastatus
      - POSTGRES_USER=idadb
      - POSTGRES_PASSWORD=fQuDTCP8Js1W

  web:
    build: 
      context: ./idastatus

    #command: ./wait-for db:5432 -- echo "doing runserver"
    command: ["./wait-for-postgres.sh", "db", "idadb", "fQuDTCP8Js1W", "python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - db

    volumes:
      - ./idastatus:/ida/code/

    ports:
      - "8000:8000"

    links:
      - db

# this service will use same image, and once the migration is done it will be stopped
  web_migrations:
    build: 
      context: ./idastatus

    command: ["./wait-for-postgres.sh", "db", "idadb", "fQuDTCP8Js1W", "python manage.py migrate"]
    depends_on:
      - db

volumes:
  db-data:
    driver: local
