version: '3.7'

services:
  db:
    image: postgres

  db-init:
    build:
      context: ./db-init
    depends_on: 
      - db
  web:
    build: 
      context: ./idastatus
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./idastatus:/ida/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
