version: '3.7'

services:
  db:
    image: postgres:11.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=idastatus
      - POSTGRES_USER=idadb
      - POSTGRES_PASSWORD=password

  web:
    build: 
      context: ./idastatus

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./idastatus:/ida/code/

    ports:
      - "8000:8000"

    links:
      - db

    depends_on:
      - db

volumes:
  db-data:
    driver: local