---
version: '3'

services:
  db:
    build:
      context: ./db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"
    # environment:
    #     POSTGRES_IDA_DB: idastatus
    #     POSTGRES_IDA_USER: idadb
    #     POSTGRES_IDA_PASSWORD: idadb
    #     POSTGRES_PASSWORD: password
    restart: unless-stopped

  web:
    hostname: web
    build:
      context: ./idastatus

    # command: ./wait-for db:5432 -- echo "doing runserver"
    command: >
        bash -c "python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn idastatus.wsgi --bind 0.0.0.0:80  --timeout 3000"
    depends_on:
      - db

    expose:
      - "80"
    volumes:
      - ./idastatus:/ida/code/

    links:
      - db
    restart: unless-stopped

  # this service provides the proxy to https connection
  web_proxies:
    image: nginx
    volumes:
      - ./nginx/nginx_aws:/etc/nginx:ro
    ports:
      - "80:80"

    depends_on:
      - "web"
    restart: unless-stopped

  # this service will use same image, and once the migration is done
  # it will be stopped
  web_migrations:
    build:
      context: ./idastatus

    command: >
        ["./wait-for-postgres.sh", "db", "idadb", "${POSTGRES_IDA_PASSWORD}",
        "python manage.py migrate"]
    depends_on:
      - db

volumes:
  db-data:
    driver: local
