version: '3'

services:
  db:
    image: postgres:11.14
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=idastatus
      - POSTGRES_USER=idadb
      - POSTGRES_PASSWORD=$POSTGRES_USER_PASSWORD
    restart: unless-stopped

  web:
    hostname: web
    build: 
      context: ./idastatus

    #command: ./wait-for db:5432 -- echo "doing runserver"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --certfile=/etc/pki/tls/certs/idastatus-dev_ucsd_edu.cer --keyfile=/etc/pki/tls/private/idastatus-dev_ucsd_edu.key idastatus.wsgi --bind 0.0.0.0:8000  --timeout 3000"    
    depends_on:
      - db

    expose:
      - "8000"
    volumes:
      - ./idastatus:/ida/code/
      - /etc/pki/tls/private/idastatus-dev_ucsd_edu.key:/etc/pki/tls/private/idastatus-dev_ucsd_edu.key:ro
      - /etc/pki/tls/certs/idastatus-dev_ucsd_edu_interm.cer:/etc/pki/tls/certs/idastatus-dev_ucsd_edu_interm.cer:ro
      - /etc/pki/tls/certs/idastatus-dev_ucsd_edu.cer:/etc/pki/tls/certs/idastatus-dev_ucsd_edu.cer:ro

    links:
      - db
    restart: unless-stopped

# this service provides the proxy to https connection
  web_proxies:
    image: nginx
    volumes:
      - ./nginx/nginx_prod:/etc/nginx:ro
      - /etc/pki/tls/private/idastatus-dev_ucsd_edu.key:/etc/pki/tls/private/idastatus-dev_ucsd_edu.key:ro
      - /etc/pki/tls/certs/idastatus-dev_ucsd_edu_interm.cer:/etc/pki/tls/certs/idastatus-dev_ucsd_edu_interm.cer:ro
      - /etc/pki/tls/certs/idastatus-dev_ucsd_edu.cer:/etc/pki/tls/certs/idastatus-dev_ucsd_edu.cer:ro
    ports:
      - "8000:8000"

    depends_on:
      - "web"
    restart: unless-stopped

# this service will use same image, and once the migration is done it will be stopped
  web_migrations:
    build: 
      context: ./idastatus

    command: ["./wait-for-postgres.sh", "db", "idadb", $POSTGRES_USER_PASSWORD, "python manage.py migrate"]
    depends_on:
      - db

volumes:
  db-data:
    driver: local
