# Generated by Django 2.2.2 on 2019-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Station code', max_length=4)),
                ('description', models.CharField(help_text='Station description', max_length=200)),
                ('country', models.CharField(help_text="Station's country code", max_length=2)),
            ],
        ),
    ]
