# Generated by Django 2.2.2 on 2019-07-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='country',
            new_name='country_code',
        ),
    ]
