# Generated by Django 2.2.11 on 2020-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelepoch',
            name='elevation',
            field=models.FloatField(default=None, help_text='Station Elevation for this channel', null=True),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='latitude',
            field=models.FloatField(default=None, help_text='Station Latitude for this channel', null=True),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='longitude',
            field=models.FloatField(default=None, help_text='Station Longitude for this channel', null=True),
        ),
    ]
