# Generated by Django 2.2.2 on 2020-01-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='Station description', max_length=100, null=True),
        ),
    ]
