# Generated by Django 2.2.2 on 2020-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelepoch',
            name='nomfreq',
            field=models.FloatField(default=None, help_text='Longitude', null=True),
        ),
    ]
