# Generated by Django 2.2.2 on 2020-05-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_description_nullable_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelepoch',
            name='flag',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
