# Generated by Django 2.2.11 on 2020-05-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200515_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(blank=True, help_text='Instrument model abbreviation', max_length=6, null=True)),
                ('description', models.CharField(blank=True, help_text='Instrument full description', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='nomfreq',
            field=models.FloatField(blank=True, default=None, help_text='Nominal frequency', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='channel_epoch',
            field=models.ForeignKey(help_text='Channel Epoch FK', null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.ChannelEpoch'),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='code',
            field=models.CharField(blank=True, help_text='Channel code', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='depth',
            field=models.FloatField(blank=True, help_text='Instrument Overburden Depth (km)', null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='elevation',
            field=models.FloatField(blank=True, default=None, help_text='Elevation for this channel (km)', null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='end_date',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, help_text='Epoch End Date', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='latitude',
            field=models.FloatField(blank=True, default=None, help_text='Latitude for this channel', null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='location_code',
            field=models.CharField(blank=True, help_text='Location code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='longitude',
            field=models.FloatField(blank=True, default=None, help_text='Longitude for this channel', null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='start_date',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, help_text='Epoch Start Date', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='channelepoch',
            name='station',
            field=models.ForeignKey(help_text='Station code', null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='station',
            field=models.ForeignKey(help_text='Station FK', on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='elevation',
            field=models.FloatField(blank=True, default=None, help_text='Station Elevation', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, default=None, help_text='Station Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, default=None, help_text='Station Longitude', null=True),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='instype',
            field=models.ForeignKey(help_text='Instype FK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stations.Instype'),
        ),
    ]
