# Generated by Django 2.2.2 on 2019-09-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20190820_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelepoch',
            old_name='chn',
            new_name='chan',
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='station_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='storage_format',
            field=models.CharField(blank=True, choices=[('ONE', 'First One'), ('TWO', 'Second One'), ('THREE', 'Third One')], help_text='Storage Format', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='channelepoch',
            name='vang',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='geo_datum',
            field=models.CharField(blank=True, choices=[('ONE', 'First One'), ('TWO', 'Second One'), ('THREE', 'Third One')], help_text='Geodetic Positioning System', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Network'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decifac', models.BigIntegerField()),
                ('dfile', models.CharField(blank=True, max_length=200, null=True)),
                ('dir', models.CharField(blank=True, max_length=200, null=True)),
                ('gcalib', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('gnom', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('iunits', models.CharField(blank=True, max_length=200, null=True)),
                ('ounits', models.CharField(blank=True, max_length=200, null=True)),
                ('srate', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
            ],
        ),
        migrations.CreateModel(
            name='IrisWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chan', models.CharField(blank=True, max_length=4, null=True)),
                ('end_t', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('loc', models.CharField(blank=True, max_length=2, null=True)),
                ('sta', models.CharField(blank=True, max_length=4, null=True)),
                ('start_t', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
            ],
        ),
        migrations.CreateModel(
            name='IrisEpoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chan', models.CharField(blank=True, max_length=4, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('end_t', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('loc', models.CharField(blank=True, max_length=2, null=True)),
                ('sta', models.CharField(blank=True, max_length=4, null=True)),
                ('start_t', models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Station')),
            ],
        ),
    ]
