# Generated by Django 2.2.2 on 2019-10-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_added_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelepoch',
            name='edepth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='elev',
            field=models.FloatField(help_text='Elevation', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(help_text='Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.FloatField(help_text='Longitude', null=True),
        ),
    ]
