# Generated by Django 2.2.11 on 2020-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20200522_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irisepoch',
            old_name='sta',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='irisepoch',
            old_name='begt',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='irisepoch',
            old_name='loc',
            new_name='location_code',
        ),
        migrations.RenameField(
            model_name='irisepoch',
            old_name='endt',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='iriswithdraw',
            old_name='sta',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='iriswithdraw',
            old_name='begt',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='iriswithdraw',
            old_name='loc',
            new_name='location_code',
        ),
        migrations.RenameField(
            model_name='iriswithdraw',
            old_name='endt',
            new_name='start_date',
        ),
    ]
