# Generated by Django 2.2.2 on 2019-10-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20191023_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='elev',
            field=models.FloatField(default=None, help_text='Elevation', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(default=None, help_text='Latitude', null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.FloatField(default=None, help_text='Longitude', null=True),
        ),
    ]
