# Generated by Django 2.2.13 on 2020-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_update_channelepoch_FK_in_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='data_dir',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='data_file_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_gain',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=17, null=True),
        ),
    ]
