# Generated by Django 2.2.2 on 2019-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_default_floats_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='addr1',
            field=models.CharField(blank=True, default=None, help_text='Address field 1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='addr2',
            field=models.CharField(blank=True, default=None, help_text='Address field 2', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='altcode',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, default=None, help_text='City', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(help_text='Station code', max_length=4),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(blank=True, default=None, help_text='Country', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='country_code',
            field=models.CharField(default=None, help_text="Station's country code", max_length=2),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.CharField(default=None, help_text='Station description', max_length=200),
        ),
        migrations.AlterField(
            model_name='station',
            name='end_t',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='geology_descr',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='histcode',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='loc_descr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='postal_code',
            field=models.CharField(blank=True, default=None, help_text='Postal Code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='province',
            field=models.CharField(blank=True, default=None, help_text='Province', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='start_t',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status_descr',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status_updated',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='vault_descr',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
