# Generated by Django 2.2.13 on 2020-09-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_added_data_fields_and_stage_gain_to_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, help_text='Unit name', max_length=100, null=True)),
                ('description', models.CharField(blank=True, help_text='Unit description', max_length=100, null=True)),
            ],
        ),
    ]
