# Generated by Django 2.2.16 on 2020-10-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_demo1'),
        ('stations', '0008_added_units_table'),
    ]

    operations = [
    ]
