# Generated by Django 2.2.18 on 2022-02-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_merge_20201002_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='dfile',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='dir',
        ),
    ]
