# Generated by Django 2.2.18 on 2022-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20220219_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='gcalib',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Calibration sensitivity factor', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gnom',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Nominal sensitivity', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_gain',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=17, null=True),
        ),
    ]
