# Generated by Django 2.2.18 on 2022-04-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_increase_gnom_decimal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='decimation_input_sample_rate',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gcalib',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Calibration sensitivity factor', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gnom',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Nominal sensitivity', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_gain',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=17, null=True),
        ),
    ]
