# Generated by Django 2.2.18 on 2022-04-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_increase_gnom_gcalib_stage_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='decimation_input_sample_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gcalib',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Calibration sensitivity factor', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='gnom',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Nominal sensitivity', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_gain',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
