# Generated by Django 2.2.18 on 2022-04-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0020_increase_leadfac_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='leading_factor',
            field=models.DecimalField(blank=True, decimal_places=9, default=None, help_text='Leading Factor', max_digits=35, null=True),
        ),
    ]
